name: Test

on: [push, pull_request]

env:
  JAVA_OPTS: '-XX:+TieredCompilation -XX:TieredStopAtLevel=1'

jobs:

  rake-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_DATABASE: ar_bogacs
        ports:
            - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      AR_ADAPTER: mysql2
      AR_VERSION: "~> 4.2"
      HIKARI_VERSION: 2.3.12

    strategy:
      matrix:
        java-version: [ 11 ]
        ruby-version: [ jruby-9.3.6.0 ]
        include:
          - java-version: 11
            ruby-version: jruby-9.2.20.1
          - java-version: 11
            ruby-version: jruby-9.2.10.0
          - java-version: 17
            ruby-version: jruby-9.2.20.1
          - java-version: 8
            ruby-version: jruby-9.2.9.0
          - java-version: 8
            ruby-version: jruby-9.1.17.0
      fail-fast: false

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up java ${{ matrix.java-version }}
        uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ matrix.java-version }}

      - name: set up ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: install bundler
        run: jruby -S gem install bundler -v "~>2.2.28"

      - name: bundle install
        run: jruby -S bundle install

      - name: download jars
        run: jruby -rbundler/setup -S rake tomcat:jndi:download tomcat:jdbc:download tomcat:dbcp:download hikari:download
        shell: bash

      - name: rake test
        run: jruby -rbundler/setup -S rake test
        shell: bash
